### ISSUE TITLE
Housekeeping: Split update_images and test_update_images

### ISSUE THREAD

**Issue by FKolwa** [redhatcloudx/rhelocator#29]
The catch all *update_images files are getting too long. Let's split them up and introduce some structure into the project.

**Comment by miyunari** [comment]
I am not sure if I 100% sure, what you mean. Could you please point me to the exact place? :)

**Comment by major** [comment]
So we have three different clouds with functions inside `update_images.py`. It might be nice to split them up into aws/azure/gcp files in the same directory so they're easier to manage. It would help if we're chasing a bug since we would know exactly where to go and we would have less code to look at.

**Comment by major** [comment]
I'm happy to start one as an example if that helps.

**Comment by miyunari** [comment]
Ah ok, so you mean we should split the file like this: `update_images.py` => `update_gcp_images.py`, `update_aws_images.py`, `update_azure_images.py`?  :)
